apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/part-of: observability-stack
    app.kubernetes.io/component: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.23.3
    helm:
      values: |
        tempo:
          metricsGenerator:
            enabled: true
            remoteWriteUrl: "http://prometheus-stack-kube-prom-prometheus.observability:9090/api/v1/write"
          overrides:
            defaults:
              metrics_generator:
                processors:
                  - service-graphs
                  - span-metrics
                  - local-blocks
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

